import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PrimeReactProvider, PrimeReactContext } from "primereact/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen p-0 sm:p-8 flex flex-col gap-5 items-center justify-center`}
      >
        <PrimeReactProvider>
          <img
            src="./logo.png"
            className="max-w-60 w-full mb-10 mt-10"
            alt=""
          />
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
